### ISSUE TITLE
node_curve.cc:20:17: error: variable has incomplete type 'void'

### ISSUE THREAD

**Issue by ghazel** [MystK/node-curve25519#2]
```
$ clang -v
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

```C
> curve25519-n2@1.1.3 install /usr/local/lib/node_modules/node-appletv/node_modules/curve25519-n2
> node-gyp rebuild

  CXX(target) Release/obj.target/curve/node_curve.o
../node_curve.cc:20:17: error: variable has incomplete type 'void'
extern "C" void init (Handle<Object>);
                ^
../node_curve.cc:20:23: error: use of undeclared identifier 'Handle'
extern "C" void init (Handle<Object>);
                      ^
../node_curve.cc:20:30: error: 'Object' does not refer to a value
extern "C" void init (Handle<Object>);
                             ^
/Users/ghazel/Library/Caches/node-gyp/12.10.0/include/node/v8.h:3369:17: note: declared here
class V8_EXPORT Object : public Value {
                ^
../node_curve.cc:20:37: error: expected expression
extern "C" void init (Handle<Object>);
                                    ^
../node_curve.cc:28:64: error: no matching member function for call to 'ToObject'
  unsigned char* arg0 = (unsigned char*) Buffer::Data(info[0]->ToObject());
                                                      ~~~~~~~~~^~~~~~~~
/Users/ghazel/Library/Caches/node-gyp/12.10.0/include/node/v8.h:2545:44: note: candidate function not viable: requires single argument 'context', but no
      arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/ghazel/Library/Caches/node-gyp/12.10.0/include/node/v8.h:2559:31: note: candidate function not viable: requires single argument 'isolate', but no
      arguments were provided
                Local<Object> ToObject(Isolate* isolate) const);
                              ^
../node_curve.cc:29:64: error: no matching member function for call to 'ToObject'
  unsigned char* arg1 = (unsigned char*) Buffer::Data(info[1]->ToObject());
                                                      ~~~~~~~~~^~~~~~~~
/Users/ghazel/Library/Caches/node-gyp/12.10.0/include/node/v8.h:2545:44: note: candidate function not viable: requires single argument 'context', but no
      arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/ghazel/Library/Caches/node-gyp/12.10.0/include/node/v8.h:2559:31: note: candidate function not viable: requires single argument 'isolate', but no
      arguments were provided
                Local<Object> ToObject(Isolate* isolate) const);
                              ^
../node_curve.cc:30:64: error: no matching member function for call to 'ToObject'
  unsigned char* arg2 = (unsigned char*) Buffer::Data(info[2]->ToObject());
                                                      ~~~~~~~~~^~~~~~~~
/Users/ghazel/Library/Caches/node-gyp/12.10.0/include/node/v8.h:2545:44: note: candidate function not viable: requires single argument 'context', but no
      arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/ghazel/Library/Caches/node-gyp/12.10.0/include/node/v8.h:2559:31: note: candidate function not viable: requires single argument 'isolate', but no
      arguments were provided
                Local<Object> ToObject(Isolate* isolate) const);
                              ^
../node_curve.cc:34:17: error: variable has incomplete type 'void'
extern "C" void init (Handle<Object> target) {
                ^
../node_curve.cc:34:23: error: use of undeclared identifier 'Handle'
extern "C" void init (Handle<Object> target) {
                      ^
../node_curve.cc:34:30: error: 'Object' does not refer to a value
extern "C" void init (Handle<Object> target) {
                             ^
/Users/ghazel/Library/Caches/node-gyp/12.10.0/include/node/v8.h:3369:17: note: declared here
class V8_EXPORT Object : public Value {
                ^
../node_curve.cc:34:38: error: use of undeclared identifier 'target'
extern "C" void init (Handle<Object> target) {
                                     ^
../node_curve.cc:34:45: error: expected ';' after top level declarator
extern "C" void init (Handle<Object> target) {
                                            ^
                                            ;
12 errors generated.
make: *** [Release/obj.target/curve/node_curve.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/Cellar/node/12.10.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/node-appletv/node_modules/curve25519-n2
gyp ERR! node -v v12.10.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! curve25519-n2@1.1.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the curve25519-n2@1.1.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by MystK** [comment]
this should be fixed. Please try again
